{
  "formatVersion": "1.1",
  "component": {
    "url": "../../store5/5.0.0-SNAPSHOT-zest/store5-5.0.0-SNAPSHOT-zest.module",
    "group": "org.mobilenativefoundation.store",
    "module": "store5",
    "version": "5.0.0-SNAPSHOT-zest",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.mobilenativefoundation.store",
          "module": "multicast5",
          "version": {
            "requires": "5.0.0-SNAPSHOT-zest"
          }
        },
        {
          "group": "org.mobilenativefoundation.store",
          "module": "cache5",
          "version": {
            "requires": "5.0.0-SNAPSHOT-zest"
          }
        }
      ],
      "files": [
        {
          "name": "store.klib",
          "url": "store5-iosarm64-5.0.0-SNAPSHOT-zest.klib",
          "size": 133436,
          "sha512": "b907ca2198f15090ff7d50709bd537c1e23b32206f872a8f3cdd00f0ce1e55791b85d54eced7bcb3e05fa0ba3f47d223d773b58365cfe5d3b5ebce8f4d697687",
          "sha256": "ecb8549aeb079f96c2ea431c16ed48a95074a9c4cac3f7991213c5c45a95a33d",
          "sha1": "38fc86ddc532ccd5a96b5518a67ffaf7e4f0f52e",
          "md5": "4f4dfa32b205e9ea4e4e4c91d40adc8c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.mobilenativefoundation.store",
          "module": "multicast5",
          "version": {
            "requires": "5.0.0-SNAPSHOT-zest"
          }
        },
        {
          "group": "org.mobilenativefoundation.store",
          "module": "cache5",
          "version": {
            "requires": "5.0.0-SNAPSHOT-zest"
          }
        }
      ],
      "files": [
        {
          "name": "store-iosarm64-5.0.0-SNAPSHOT-zest-metadata.jar",
          "url": "store5-iosarm64-5.0.0-SNAPSHOT-zest-metadata.jar",
          "size": 261,
          "sha512": "abb65bfc9d36a33083f0a361af2efce70a0a9aa9ed58ce238e6f95b0f34059706e70cc6b30914db7c0c36428c7f73dc3c79a7f2b1cb97afefed42952b10b6a2d",
          "sha256": "3e795c58f5b584edb191cb0072a49e8a186a7228ecdbcbc19bbe9c72c7562687",
          "sha1": "b2634372fb26df908dddf01d587285af85a6a430",
          "md5": "fd7dd32c1aeaaa204a59518c73d5eb1c"
        }
      ]
    }
  ]
}
