{
  "formatVersion": "1.1",
  "component": {
    "url": "../../store5/5.0.0-SNAPSHOT-zest/store5-5.0.0-SNAPSHOT-zest.module",
    "group": "org.mobilenativefoundation.store",
    "module": "store5",
    "version": "5.0.0-SNAPSHOT-zest",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.mobilenativefoundation.store",
          "module": "multicast5",
          "version": {
            "requires": "5.0.0-SNAPSHOT-zest"
          }
        },
        {
          "group": "org.mobilenativefoundation.store",
          "module": "cache5",
          "version": {
            "requires": "5.0.0-SNAPSHOT-zest"
          }
        }
      ],
      "files": [
        {
          "name": "store.klib",
          "url": "store5-iossimulatorarm64-5.0.0-SNAPSHOT-zest.klib",
          "size": 133522,
          "sha512": "dff605570baff52603ee12ff5cb72413e36bb6e3b3e23ad6f3cbf5f70b9af9abc7885610ad4d794dd82f44a48aa3c4049571d2db634b5fb216b42b5dffd373a5",
          "sha256": "6c2e522831fc477849306a41cea842c546d2c6ae6caee870b71c8cad92983feb",
          "sha1": "ba3d57019c13d5fb85964b03b2cc3f35cc56ca94",
          "md5": "5ede2a3945e8cbda84fb7249401d53d3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.mobilenativefoundation.store",
          "module": "multicast5",
          "version": {
            "requires": "5.0.0-SNAPSHOT-zest"
          }
        },
        {
          "group": "org.mobilenativefoundation.store",
          "module": "cache5",
          "version": {
            "requires": "5.0.0-SNAPSHOT-zest"
          }
        }
      ],
      "files": [
        {
          "name": "store-iossimulatorarm64-5.0.0-SNAPSHOT-zest-metadata.jar",
          "url": "store5-iossimulatorarm64-5.0.0-SNAPSHOT-zest-metadata.jar",
          "size": 261,
          "sha512": "abb65bfc9d36a33083f0a361af2efce70a0a9aa9ed58ce238e6f95b0f34059706e70cc6b30914db7c0c36428c7f73dc3c79a7f2b1cb97afefed42952b10b6a2d",
          "sha256": "3e795c58f5b584edb191cb0072a49e8a186a7228ecdbcbc19bbe9c72c7562687",
          "sha1": "b2634372fb26df908dddf01d587285af85a6a430",
          "md5": "fd7dd32c1aeaaa204a59518c73d5eb1c"
        }
      ]
    }
  ]
}
