{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multicast5/5.0.0-SNAPSHOT-zest/multicast5-5.0.0-SNAPSHOT-zest.module",
    "group": "org.mobilenativefoundation.store",
    "module": "multicast5",
    "version": "5.0.0-SNAPSHOT-zest",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "multicast.klib",
          "url": "multicast5-iosx64-5.0.0-SNAPSHOT-zest.klib",
          "size": 35927,
          "sha512": "4b0a474cea27413f151f3799d4807a0088fb84841dc3521f1905c1d0961d91d385cda5152c176a36d4cbeab89115ebd83c063d7c6c5da995161f7c9bb023aaed",
          "sha256": "83fba64afcf1e0a153a5c174328e762dbe2efc6d033ffee526cd4ca9744c898e",
          "sha1": "8e03939109ff3993edcdf48c2b759fba190fce81",
          "md5": "012ed085094a5b911d2ec2b7e6f70725"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "multicast-iosx64-5.0.0-SNAPSHOT-zest-metadata.jar",
          "url": "multicast5-iosx64-5.0.0-SNAPSHOT-zest-metadata.jar",
          "size": 261,
          "sha512": "abb65bfc9d36a33083f0a361af2efce70a0a9aa9ed58ce238e6f95b0f34059706e70cc6b30914db7c0c36428c7f73dc3c79a7f2b1cb97afefed42952b10b6a2d",
          "sha256": "3e795c58f5b584edb191cb0072a49e8a186a7228ecdbcbc19bbe9c72c7562687",
          "sha1": "b2634372fb26df908dddf01d587285af85a6a430",
          "md5": "fd7dd32c1aeaaa204a59518c73d5eb1c"
        }
      ]
    }
  ]
}
