{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cache5/5.0.0-SNAPSHOT-zest/cache5-5.0.0-SNAPSHOT-zest.module",
    "group": "org.mobilenativefoundation.store",
    "module": "cache5",
    "version": "5.0.0-SNAPSHOT-zest",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "cache.klib",
          "url": "cache5-iosx64-5.0.0-SNAPSHOT-zest.klib",
          "size": 82336,
          "sha512": "e6e492d90472ebbb92fe7a923c20b1a6897ab2e455c72b86b4ca75967b1e2c1695bbc0f27d2c076efaf7099418805afe352b43f2b620d690a664a756483fa208",
          "sha256": "04a13cb1692da4eb68c485c520ec8124a69e0c343359c578df83192a6600fae7",
          "sha1": "573c56ce7b965943662af2538bd7689ecb1cc716",
          "md5": "a6438b55e69aa281696236b936616a52"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "cache-iosx64-5.0.0-SNAPSHOT-zest-metadata.jar",
          "url": "cache5-iosx64-5.0.0-SNAPSHOT-zest-metadata.jar",
          "size": 261,
          "sha512": "becff474f63decc59cdfe850e02356e729c5ff4c154619b4843a7aab1fcbd494b4bd285becd3b91ab30893b612404b010a55df647ba47adab6bd608913cbb81b",
          "sha256": "db0102f2d69008c8e2bcd21de88d3f86f21ca868a564bad561e7331efa5db9aa",
          "sha1": "bbda9c04eddcea821c9f93801eda29d99ba79834",
          "md5": "54aaefac2549790b54947ac7aedb014f"
        }
      ]
    }
  ]
}
