{
  "formatVersion": "1.1",
  "component": {
    "url": "../../cache5/5.0.0-SNAPSHOT-zest/cache5-5.0.0-SNAPSHOT-zest.module",
    "group": "org.mobilenativefoundation.store",
    "module": "cache5",
    "version": "5.0.0-SNAPSHOT-zest",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "cache.klib",
          "url": "cache5-iosarm64-5.0.0-SNAPSHOT-zest.klib",
          "size": 82352,
          "sha512": "ba94cf0e440711ec67bcbf836f6c893c088d8942eb4d0ce8349b48bb4156c81963cec8203d8cb6d345bd2ddd7b0a61128794439feae3701915298e882e8621d1",
          "sha256": "f56691923125c5efa85a33ad35f16ec5308bb4f510df291f8e60ef673b3bc562",
          "sha1": "3f5b176b67ab5b0042b1ee782fc5eac4c7e3b135",
          "md5": "1b7642fa1bea79682cc26c79a685efb6"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.18.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "cache-iosarm64-5.0.0-SNAPSHOT-zest-metadata.jar",
          "url": "cache5-iosarm64-5.0.0-SNAPSHOT-zest-metadata.jar",
          "size": 261,
          "sha512": "becff474f63decc59cdfe850e02356e729c5ff4c154619b4843a7aab1fcbd494b4bd285becd3b91ab30893b612404b010a55df647ba47adab6bd608913cbb81b",
          "sha256": "db0102f2d69008c8e2bcd21de88d3f86f21ca868a564bad561e7331efa5db9aa",
          "sha1": "bbda9c04eddcea821c9f93801eda29d99ba79834",
          "md5": "54aaefac2549790b54947ac7aedb014f"
        }
      ]
    }
  ]
}
